--- 
title: "Ocean Health Index Onboarding"
author: "OHI Team"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is onboarding learning roadmap to lead Ocean Health Index assessments"
---

# Welcome {#welcome}

Hello! This book has onboarding resources for the Ocean Health Index (OHI). It is meant as an annotated learning roadmap for groups that are interested in leading your own OHI+ assessment.

## What is this book?

This book aims to help you get "on board" with Ocean Health Index (OHI) methods and practices. There are a lot of moving pieces to leading your own OHI assessment - called OHI+ - and it's important to set yours up in a way that is organized and collaborative, expecting that team members might change and that methods might be revisited. So building in resilience and focusing on documentation and sharing from the beginning is critical. 

<!---Note: this roadmap is to help you lead your own OHI+ assessment. Something about OHI-Go https://ohi-science.org/projects/ohi-go/--->

Orient to the book, the websites, “github repos”
Ohi-science.org incl ohi-global, OHI+ websites.
Oceanhealthindex.org? Website
books


<!---

## Suggested Agenda

| Time        |                                                        Day 1|                                          Day 2|
|:------------|------------------------------------------------------------:|----------------------------------------------:|
| 9-10:30     |  [Motivation](#overview), [R & RStudio, RMarkdown](#rstudio)|              [Charts with `ggplot2`](#ggplot2)|
| break       |                                                             |                                               |
| 11-12:30    |                                   [Intro to GitHub](#github)|  [`dplyr` & Pivot Tables](#dplyr-pivot-tables)|
| lunch       |                                                             |                                               |
| 13:00-14:30 |                          [Importing data: `readxl`](#readxl)|          [`dplyr` & VLOOKUPs](#dplyr-vlookups)|

--->
